import 'package:get/get.dart';
import 'package:rapid_app/res/values/strings.dart';

class StringsTrans extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          Strings.kAppName: 'Rapid App',
          Strings.kContinue: 'Continue',
          Strings.kUrl: 'Url',
          Strings.kUserName: 'User Name',
          Strings.kPassword: 'Password',
          Strings.kLogin: 'Login',
          Strings.kLoginTitle: 'Login to continue',
          Strings.kDashboard: 'Dashboard',
          Strings.kHome: 'Home',
          Strings.kCalendar: 'calendar',
          Strings.kAdd: 'Add',
          Strings.kSearch: 'Search',
          Strings.kCommonSearch: 'Common Search',
          Strings.kAdvanceSearch: 'Advance Search',
          Strings.kFilter: 'Filter',
          Strings.kAddColumns: 'Add Columns',
          Strings.kExportExcel: 'Export to Excel',
          Strings.kExportPdf: 'Export to Pdf',
          Strings.kSearchHint: 'Search here...',
          Strings.kOk: 'Ok',
          Strings.kSubmit: 'Submit',
          Strings.kAddProject: 'Add Project',
          Strings.kEditProject: 'Edit Project',
          Strings.kProjectName: 'Project Name',
          Strings.kProjects: 'Projects',
          Strings.kDelete: 'Delete',
          Strings.kChangePassword: 'Change Password',
          Strings.kSettings: 'Settings',
          Strings.kCancel: 'Cancel',
          Strings.kLogout: 'Logout',
          Strings.kLogoutMessage: 'Are you sure that you want to logout?',
          Strings.kNever: 'Never',
          Strings.kDaily: 'Daily',
          Strings.kWeekly: 'Weekly',
          Strings.kMonthly: 'Monthly',
          Strings.kYearly: 'Yearly',
          Strings.kShare: 'Share',
          Strings.kScreenShort: 'Screen Short',
          Strings.kEnd: 'End',
          Strings.kStart: 'Start',
          Strings.kVersion: 'Version',
          Strings.kUrlErrorMsg: 'This url could not be found or Invalid url',
          Strings.kMessage: 'Message',
          Strings.kConnectionError: 'Connection Error',
          Strings.kSomethingWentWrong: 'something went wrong',
          Strings.kInvalidEntry: 'Invalid entry',
          Strings.kInvalidProjectName: 'Invalid project name',
          Strings.kInvalidUrl: 'Invalid url',
          Strings.kEditDetails: 'Edit Details',
          Strings.kAddDetails: 'Add Details',
          Strings.kSave: 'Save',
          Strings.kSelectDate: 'Select Date',
          Strings.kUpdate: 'Update',
          Strings.kPhotoLibrary: 'PhotoLibrary',
          Strings.kGallery: 'Gallery',
          Strings.kCamera: 'Camera',
          Strings.kCacheMenus: 'Cache Menus',
          Strings.kOnlineOffline: 'Online/Offline',
          Strings.kOnlineSave: 'Online Save',
          Strings.kOfflineSave: 'Offline Save',
          Strings.kOfflineDataSyncing: 'Offline Data Syncing',
          Strings.kSync: 'Sync',
          Strings.kSaveToLocal: 'Save to local',
        },
      };
}
